name: macOS
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: CXX version
        run: clang++ --version
      - name: make setup
        run: make setup
      - name: make bin/elektroviz
        run: make build
      - name: "export binary"
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/elektroviz
      - name: make clean
        run: make clean
