name: macOS
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: CXX version
        run: '"$(brew --prefix llvm@18)"/bin/clang++ --version'
      - name: make setup
        run: make setup
      - name: make build
        run: CXX="$(brew --prefix llvm@18)/bin/clang++" make build
      - name: "export binary"
        uses: actions/upload-artifact@v4
        with:
          name: elektroviz
          path: build/macOS/release/elektroviz
      - name: make clean
        run: make clean
