name: Ubuntu
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: update apt
        run: sudo apt-get update
      - name: install raylib dependencies
        run: sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
      - name: CXX version
        run: clang++ --version
      - name: make setup
        run: make setup
      - name: make build
        run: make build
        env:
          CXX: clang++
      - name: "export binary"
        uses: actions/upload-artifact@v4
        with:
          name: elektroviz
          path: build/Linux/release/elektroviz
      - name: make clean
        run: make clean
